export enum PERMISSIONS_TYPE {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
  BLOCKED = 'BLOCKED',
}

export enum REQUESTS_PERMISSIONS_TYPE {
  PENDING = 'PENDING',
  APPROVED = 'ACCEPT',
}
